/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DayManager")]
    [LuaRegisterType(0xc364a337e4cd3a94, typeof(LuaBehaviour))]
    public class DayManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "53d2eb28475036448a7b01a64892cdca";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_cameraRoot = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_dayGameObjects = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_cameraRoot),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_dayGameObjects),
            };
        }
    }
}

#endif
