/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DiscoveredAnimationManager")]
    [LuaRegisterType(0x488abe6a71a6d6ce, typeof(LuaBehaviour))]
    public class DiscoveredAnimationManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9b758fdf1d4a0044ca6ac9fb565a48cf";
        public override string ScriptGUID => s_scriptGUID;


        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
            };
        }
    }
}

#endif
