/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/NpcTitle")]
    [LuaRegisterType(0x606ba258eafa17e6, typeof(LuaBehaviour))]
    public class NpcTitle : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1cc131ce680926046889112cc21abb12";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Color m_backgroundColor = new Color(0f, 0f, 0f, 1f);
        [SerializeField] public System.String m_npcTitle = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_backgroundColor),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_npcTitle),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
            };
        }
    }
}

#endif
