/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PokeableObject")]
    [LuaRegisterType(0xf1481a27f0355313, typeof(LuaBehaviour))]
    public class PokeableObject : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a99089f9e1eb68b4db7b9bd2ba38d3bf";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_soundName = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_soundName),
            };
        }
    }
}

#endif
