/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SimonSaysTapListener")]
    [LuaRegisterType(0xa6719cf43a7dae2, typeof(LuaBehaviour))]
    public class SimonSaysTapListener : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "2b881a61ddd9a1142a25cc26c4284e30";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_id = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_id),
            };
        }
    }
}

#endif
